class LabelMapper {

    // TODO: retrieve dynamically from config entities
    static fieldNameToLabelMap = {
        "Parent" : "Parent Account",
        "companyName" : "Company Name",
        "leadId" : "Source Lead",
        "industry" : "Industry",
        "revenue" : "Yearly Revenue",
        "billingAddress" : "Billing Address",
        "description" : "Description",
        "type" : "Type",
        "website" : "Website",
        "clientRating" : "Client Rating",
        "vat" : "VAT",
        "parent" : "Parent",
        "active" : "Is Active",
        "firstName" : "First Name",
        "lastName" : "Last Name",
        "email" : "Email",
        "phone" : "Phone",
        "mobile" : "Mobile",
        "prefix" : "Prefix",
        "birthdate" : "Birthdate",
        "department" : "Department",
        "role" : "Role",
        "account" : "Related Account",
        "companyAddress" : "Company Address",
        "companyIndustry" : "Company Industry",
        "contactPerson" : "Contact Person",
        "contactPrefix" : "Contact Prefix",
        "contactMobile" : "Contact Mobile",
        "contactPhone" : "Contact Phone",
        "contactRole" : "Contact Role",
        "contactEmail" : "Contact Email",
        "status" : "Status",
        "id" : "Id",
        "created": "Created On",
        "modified": "Last Updated On",
        "title": "Title",
        "comments": "Comments",
        "expectedRevenue" : "Expected Revenue",
        "relatedAccount" : "Related Account",
        "relatedLead" : "Related Lead",
        "relatedOpportunity" : "Related Opportunity",
        "dueDate" : "Due Date",
        "reason" : "Reason",
        "name" : "Name",
        "severity": "Severity",
        "source" : "Source",
        "category" : "Category",
        "createdDate": "Created Date",
        "relatedContact" : "Related Contact",
        "closedDate": "Closed Date",
        "agentName": "Agent Name",
        "relatedCase" : "Related Case",
        "duration" : "Duration (in seconds)",
        "callDate" : "Call Date",
        "customerPhone" : "Customer Phone"

    }
}

export default LabelMapper